version: '3.8'

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - '27017:27017'

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      RESET_SECRET: ${RESET_SECRET}
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
